#!/usr/bin/env bash
# debugging nginx port 80
# Solution: delete the existing ../sites-enabled/defaul,
# and replace it with a copy of../sites-available/default. 
# No need to create a symbolic link. 
# NB: The flag -s functions to create a symbolic link,
# -f deletes the existing file and replaces it
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
